/// All GTK widgets constructed for the main window, passed to the wiring phase.
struct WindowWidgets {
    win: adw::ApplicationWindow,
    root: adw::ToolbarView,
    header: adw::HeaderBar,
    outer_ovl: gtk::Overlay,
    video_handle: gtk::WindowHandle,
    gl_area: gtk::GLArea,
    bottom: gtk::Box,
    #[cfg(target_os = "macos")]
    bottom_shell: gtk::Box,
    play_pause: gtk::Button,
    sibling_nav: SiblingNavUi,
    menu_btn: gtk::MenuButton,
    vol_menu: gtk::MenuButton,
    vol_header_img: gtk::Image,
    vol_readout: gtk::Label,
    sub_menu: gtk::MenuButton,
    sub_readout: gtk::Label,
    speed_mbtn: gtk::MenuButton,
    speed_readout: gtk::Label,
    smooth_btn: gtk::Button,
    smooth_status: gtk::Label,
    speed_list: gtk::ListBox,
    speed_sync: Rc<Cell<bool>>,
    seek: gtk::Scale,
    seek_adj: gtk::Adjustment,
    time_left: gtk::Label,
    time_right: gtk::Label,
    vol_adj: gtk::Adjustment,
    vol_mute_btn: gtk::ToggleButton,
    audio_tracks_box: gtk::Box,
    audio_tracks_block: Rc<Cell<bool>>,
    audio_tracks_section: gtk::Box,
    sub_tracks_box: gtk::Box,
    sub_tracks_block: Rc<Cell<bool>>,
    sub_tracks_section: gtk::Box,
    sub_scale_adj: gtk::Adjustment,
    sub_color_btn: gtk::ColorDialogButton,
    sub_color_row: gtk::Box,
    vol_pop: gtk::Popover,
    sub_pop: gtk::Popover,
    #[cfg(target_os = "macos")]
    main_menu: gio::Menu,
    pref_menu: gio::Menu,
    recent_scrl: gtk::Box,
    flow_recent: gtk::Box,
    recent_spacers: [gtk::Box; 2],
    undo_bar: crate::recent_view::UndoBar,
    notice_toast: crate::recent_view::NoticeToast,
    /// Local wall-clock readout; visible only in fullscreen (`docs/features/17-window-behavior.md`).
    fs_clock: gtk::Label,
    /// macOS GTK: optional label in [`adw::HeaderBar::title_widget`] so double-click toggles fullscreen.
    hdr_title_mirror: Option<Rc<gtk::Label>>,
    /// Bottom-bar `app.close-video`; tooltip from [sync_close_video_action].
    close_video_btn: gtk::Button,
    blackout_sync: Rc<crate::screen_blackout::BlackoutSync>,
    /// Keeps header [`gtk::SizeGroup`] alive for the window lifetime.
    _header_btn_heights: gtk::SizeGroup,
}
