const SMOOTH_SETUP_TEXT: &str = r#"# Smooth 60 needs all three parts:
# 1. VapourSynth Python module
# 2. MVTools plugin (libmvtools.so)
# 3. mpv/libmpv built with the vapoursynth video filter

# Debian/Ubuntu packages and vsrepo:
sudo apt-get update
sudo apt-get install vapoursynth vapoursynth-python3 libvapoursynth-dev pipx p7zip-full git meson ninja-build pkg-config build-essential
pipx install vsrepo
pipx ensurepath

# Open a new terminal after pipx ensurepath, then:
vsrepo update
vsrepo install mvtools

# Verify VapourSynth + MVTools:
python3 - <<'PY'
from pathlib import Path
import vapoursynth as vs

try:
    print(vs.core.mv)
except AttributeError:
    hits = sorted(Path.home().glob(
        ".local/share/pipx/venvs/vsrepo/lib/python*/site-packages/"
        "vapoursynth/plugins/vsrepo/libmvtools.so"
    ))
    if not hits:
        raise
    vs.core.std.LoadPlugin(str(hits[0]))
    print(vs.core.mv)
PY

# Check whether the mpv/libmpv on your system supports VapourSynth:
mpv -vf help 2>&1 | grep -E '^[[:space:]]*vapoursynth[[:space:]]'

# If that prints no vapoursynth line, build and install mpv + libmpv:
sudo apt-get build-dep mpv
git clone --depth 1 --branch v0.38.0 https://github.com/mpv-player/mpv.git mpv-vapoursynth
cd mpv-vapoursynth
meson setup build -Dlibmpv=true -Dvapoursynth=enabled --prefix=/usr/local
meson compile -C build
sudo meson install -C build
sudo ldconfig

# Verify the installed mpv now has the filter:
mpv -vf help 2>&1 | grep -E '^[[:space:]]*vapoursynth[[:space:]]'

# Verify the library Rhino will load:
ldconfig -p | grep libmpv
ldd /path/to/rhino-player | grep libmpv

# Notes:
# - Ubuntu source repositories must be enabled for apt-get build-dep.
# - If Meson says build.dat was generated by an old version, run:
#   meson setup build --wipe -Dlibmpv=true -Dvapoursynth=enabled --prefix=/usr/local
# - If Meson is installed in ~/.local and sudo cannot import it, use:
#   sudo env PYTHONPATH="$(python3 -m site --user-site)" "$(command -v meson)" install -C build
# - If your VapourSynth is R56 or newer, you can try a newer mpv tag.
# - /usr/local is preferred by Rhino's runpath on Linux builds from this repo."#;

fn can_find_mvtools(v: &db::VideoPrefs) -> bool {
    let cached = std::path::Path::new(v.mvtools_lib.trim());
    cached.is_file()
        || crate::paths::mvtools_from_env().is_some()
        || crate::paths::mvtools_lib_search().is_some()
}

/// Copy-paste setup instructions shown when Smooth 60 cannot attach its VapourSynth filter.
fn show_smooth_setup_dialog(app: &adw::Application) {
    let parent = app.active_window();
    let win = gtk::Window::builder()
        .modal(true)
        .title("Set Up Smooth 60 FPS")
        .default_width(720)
        .default_height(520)
        .build();
    if let Some(parent) = parent.as_ref() {
        win.set_transient_for(Some(parent));
    }
    win.set_application(Some(app));

    let area = gtk::Box::new(gtk::Orientation::Vertical, 12);
    area.set_spacing(12);
    area.set_margin_top(16);
    area.set_margin_bottom(16);
    area.set_margin_start(16);
    area.set_margin_end(16);

    let msg = gtk::Label::new(Some(
        "Rhino could not enable Smooth 60 FPS. Install VapourSynth, MVTools, and an mpv/libmpv build with VapourSynth support, then enable Smooth Video again.",
    ));
    msg.set_wrap(true);
    msg.set_xalign(0.0);
    area.append(&msg);

    let text = gtk::TextView::new();
    text.set_editable(false);
    text.set_cursor_visible(false);
    text.set_monospace(true);
    text.buffer().set_text(SMOOTH_SETUP_TEXT);

    let scroll = gtk::ScrolledWindow::builder()
        .hexpand(true)
        .vexpand(true)
        .child(&text)
        .build();
    area.append(&scroll);

    let close = gtk::Button::with_label("Close");
    close.set_halign(gtk::Align::End);
    close.connect_clicked({
        let win = win.clone();
        move |_| win.close()
    });
    area.append(&close);

    win.set_child(Some(&area));
    win.present();
}
