#[cfg(not(target_os = "macos"))]
const SMOOTH_SETUP_TEXT_LINUX: &str = r#"# Smooth 60 needs all three parts:
# 1. VapourSynth Python module
# 2. MVTools plugin (libmvtools.so)
# 3. mpv/libmpv built with the vapoursynth video filter

# Debian/Ubuntu packages and vsrepo:
sudo apt-get update
sudo apt-get install vapoursynth vapoursynth-python3 libvapoursynth-dev pipx p7zip-full git meson ninja-build pkg-config build-essential
pipx install vsrepo
pipx ensurepath

# Open a new terminal after pipx ensurepath, then:
vsrepo update
vsrepo install mvtools

# Verify VapourSynth + MVTools:
python3 - <<'PY'
from pathlib import Path
import vapoursynth as vs

try:
    print(vs.core.mv)
except AttributeError:
    hits = sorted(Path.home().glob(
        ".local/share/pipx/venvs/vsrepo/lib/python*/site-packages/"
        "vapoursynth/plugins/vsrepo/libmvtools.so"
    ))
    if not hits:
        raise
    vs.core.std.LoadPlugin(str(hits[0]))
    print(vs.core.mv)
PY

# Check whether the mpv/libmpv on your system supports VapourSynth:
mpv -vf help 2>&1 | grep vapoursynth

# If that prints no vapoursynth line, build and install mpv + libmpv:
sudo apt-get build-dep mpv
git clone --depth 1 --branch v0.38.0 https://github.com/mpv-player/mpv.git mpv-vapoursynth
cd mpv-vapoursynth
meson setup build -Dlibmpv=true -Dvapoursynth=enabled --prefix=/usr/local
meson compile -C build
sudo meson install -C build
sudo ldconfig

# Verify the installed mpv now has the filter:
mpv -vf help 2>&1 | grep vapoursynth

# Verify the library Rhino will load:
ldconfig -p | grep libmpv
ldd /path/to/rhino-player | grep libmpv

# Notes:
# - Ubuntu source repositories must be enabled for apt-get build-dep.
# - If Meson says build.dat was generated by an old version, run:
#   meson setup build --wipe -Dlibmpv=true -Dvapoursynth=enabled --prefix=/usr/local
# - If Meson is installed in ~/.local and sudo cannot import it, use:
#   sudo env PYTHONPATH="$(python3 -m site --user-site)" "$(command -v meson)" install -C build
# - If your VapourSynth is R56 or newer, you can try a newer mpv tag.
# - /usr/local is preferred by Rhino's runpath on Linux builds from this repo."#;

#[cfg(target_os = "macos")]
const SMOOTH_SETUP_TEXT_MACOS: &str = r#"# Smooth 60 on macOS needs VapourSynth + a vapoursynth-capable libmpv.
# MVTools is vendored by Rhino (not left on Homebrew paths):
#   • packaged .app  → Contents/Resources/lib/vapoursynth/plugins/mvtools.dylib
#   • cargo run      → ~/.config/rhino/lib/vapoursynth/plugins/mvtools.dylib
#                     (copied once from brew; survives `brew upgrade`)

# Install the Homebrew pieces Rhino still links at runtime:
brew install mpv vapoursynth vapoursynth-mvtools

# Verify mpv has the vapoursynth filter:
mpv -vf help 2>&1 | grep vapoursynth

# First Smooth enable (or: open Rhino once) seeds ~/.config/rhino/lib from brew.
# Or seed manually from the repo checkout:
#   ./scripts/macos-vendor-smooth-libs.sh ~/.config/rhino/lib/vapoursynth

# Verify VapourSynth + the vendored plugin:
python3 - <<'PY'
import os
from pathlib import Path
import vapoursynth as vs

candidates = [
    Path.home() / ".config/rhino/lib/vapoursynth/plugins/mvtools.dylib",
]
env = os.environ.get("RHINO_MVTOOLS_LIB")
if env:
    candidates.insert(0, Path(env))
hit = next((p for p in candidates if p.is_file()), None)
if hit is None:
    raise SystemExit("mvtools.dylib not vendored yet — run Rhino once or macos-vendor-smooth-libs.sh")
vs.core.std.LoadPlugin(path=str(hit))
print(vs.core.mv)
PY

# Optional override:
export RHINO_MVTOOLS_LIB=/full/path/to/mvtools.dylib

# Notes:
# - VapourSynth + libmpv still come from Homebrew (Python / VSScript).
# - MVTools is frozen under Rhino paths (@loader_path).
# - After `brew upgrade python`, Rhino rewrites ~/.config/vapoursynth/vapoursynth.toml
#   to opt/python@* (stale Cellar patch paths break VSScript).
# - If Homebrew mpv ever lacks the vapoursynth filter: brew reinstall mpv --build-from-source"#;
